name: posthog_dart
description: "Quick and dirty mapping for the PostHog API."
version: 0.0.1
repository: https://github.com/necodeIT/posthog_dart
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  logging: ^1.3.0
  os_detect: ^2.0.2
  uuid: ^4.5.1
